# fly.toml app configuration file generated for harmony-health-hidden-smoke-3180 on 2024-03-18T12:52:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'harmony-health-hidden-smoke-3180'
primary_region = 'mad'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'mysql'
  DB_HOST = '66.241.125.182'
  DB_DATABASE = 'harmony-health'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
